fuel-cost-api:
  container_name: fuel-cost-api
  build: ./
  net: fuel-cost-net
  ports:
    - '3000:3000'
  volumes:
    - ./:/app
  environment:
    - NODE_ENV=development
    - PORT=3000
    - MONGO_URL=mongodb://mongodb:27017
    - MONGO_DB_NAME=fuel-cost

mongo:
  container_name: mongodb
  image: mongo
  net: fuel-cost-net
  ports: 
    - '27017:27017'
