name: build

on:
  pull_request:
    branches: 
      - master
  push:	
    branches: 	
      - master
  schedule:
    - cron: '0 16 * * *'

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 10.x
        uses: actions/setup-node@v1.1.0
        with:
          node-version: 10
      - name: Install and test
        run: |
          npm ci
          npm test
