name: release

on:
  push:	
    branches: 	
      - master

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 10.x
        uses: actions/setup-node@v1.1.0
        with:
          node-version: 10
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1.2.0
      - name: Log when version changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
      - name: Install and test when version changed
        if: steps.check.outputs.changed == 'true'
        run: |
          npm ci
          npm test
